import datetime
from typing import Dict, Any
from src.config import get_threshold

def generate_sebi_scores_complaint(data: Dict[str, Any], content_type: str = "Video") -> str:
    """
    Generates a structured, legally formatted complaint draft ready for submission
    to the SEBI Complaints Redress System (SCORES) portal / SEBI Enforcement Division.
    """
    now = datetime.datetime.now().strftime("%d-%B-%Y %H:%M:%S IST")
    sebi = data.get("sebi_analysis", {})
    registry = data.get("registry_check", {})
    
    claimed_name = sebi.get("claimed_advisor_name") or "Unspecified Entity / Finfluencer"
    claimed_reg = sebi.get("claimed_registration_number") or "None Disclosed"
    reg_verdict = registry.get("verdict", "not claimed").upper()
    
    is_deepfake = data.get("is_deepfake", False)
    vision_score = data.get("vision_score", 0.0)
    audio_score = data.get("audio_score", 0.0)
    risk_score = data.get("composite_risk_score", sebi.get("composite_risk_score", 0.0))
    verdict = data.get("verdict", "Suspicious Content")
    
    # Identify violated SEBI regulations
    violations = []
    return_quotes = sebi.get("specific_return_promises", [])
    implied_quotes = sebi.get("implied_returns", [])
    urgency_quotes = sebi.get("urgency_scarcity_language", [])
    paywall_quotes = sebi.get("paywall_push", [])
    cred_quotes = sebi.get("credential_misrepresentation", [])
    
    if return_quotes or implied_quotes:
        violations.append("• SEBI (Investment Advisers) Regulations, 2013 — Prohibition of guaranteed/assured return promises.")
    if reg_verdict in ["NOT FOUND", "NAME-NUMBER MISMATCH", "MALFORMED NUMBER"]:
        violations.append("• SEBI Act, 1992 Section 12(1) — Providing investment advice/research without valid SEBI registration.")
    if paywall_quotes:
        violations.append("• SEBI Master Circular on Social Media/Finfluencers — Unlawful monetization of unregistered financial advice via private channels.")
    if is_deepfake:
        violations.append("• SEBI (Prohibition of Fraudulent and Unfair Trade Practices) Regulations, 2003 (PFUTP) — Synthetically generated deepfake media used to deceive retail investors.")
    if not violations:
        violations.append("• Potential Deceptive Marketing & Misrepresentation under SEBI PFUTP Regulations.")

    # Format Evidence Section
    evidence_lines = []
    if return_quotes:
        evidence_lines.append(f"  [Guaranteed Return Claims]:\n" + "\n".join([f'    - "{q}"' for q in return_quotes]))
    if implied_quotes:
        evidence_lines.append(f"  [Implied Return Promises]:\n" + "\n".join([f'    - "{q}"' for q in implied_quotes]))
    if urgency_quotes:
        evidence_lines.append(f"  [Urgency & Pressure Tactics]:\n" + "\n".join([f'    - "{q}"' for q in urgency_quotes]))
    if paywall_quotes:
        evidence_lines.append(f"  [Unregistered Paid Channel Funnels]:\n" + "\n".join([f'    - "{q}"' for q in paywall_quotes]))
    if cred_quotes:
        evidence_lines.append(f"  [Credential Misrepresentation / Tampering]:\n" + "\n".join([f'    - "{q}"' for q in cred_quotes]))
        
    evidence_text = "\n\n".join(evidence_lines) if evidence_lines else "  No explicit verbal quotes extracted."

    quality_info = data.get("input_quality", {})
    quality_rating = quality_info.get("rating", "Standard") if isinstance(quality_info, dict) else "Standard"

    vision_thresh = get_threshold("vision_fake_threshold", 0.5)
    audio_thresh = get_threshold("audio_fake_threshold", 0.5)
    complaint = f"""================================================================================
           SECURITIES AND EXCHANGE BOARD OF INDIA (SEBI)
   PRE-FILING EVIDENCE DOSSIER — SCORES / MARKET SURVEILLANCE REVIEW
   [PREPARED BY FINGUARD FORENSIC ASSISTANT — FOR HUMAN / COMPLIANCE OFFICER REVIEW]
================================================================================

LEGAL NOTICE & DISCLAIMER:
This document is an automated evidentiary compilation generated by the FinGuard 
Forensic Platform. It serves as an investigative dossier to support regulatory 
filings and does not constitute a judicial ruling or final determination of liability.

DATE & TIME OF GENERATION : {now}
INVESTIGATION CASE ID    : FG-SCORES-{datetime.datetime.now().strftime("%Y%m%d")}-{data.get("scan_type", "AUDIT").upper()}
RISK ASSESSMENT RATING   : {verdict.upper()}
COMPOSITE THREAT SCORE   : {risk_score * 100:.1f}%
INPUT MEDIA QUALITY      : {quality_rating}

--------------------------------------------------------------------------------
1. RESPONDENT / SUSPECT DETAILS
--------------------------------------------------------------------------------
Name of Finfluencer / Entity : {claimed_name}
Claimed SEBI Reg. Number     : {claimed_reg}
Local Registry Check (Aug 26): {reg_verdict}
Channel / Medium of Fraud    : Digital {content_type} (Social Media / Web Transmission)

--------------------------------------------------------------------------------
2. AI FORENSIC EVIDENCE ASSESSMENT
--------------------------------------------------------------------------------
• Visual Deepfake Confidence  : {vision_score * 100:.1f}% {"(SYNTHETIC FACE MANIPULATION DETECTED)" if vision_score > vision_thresh else "(Within Normal Parameters)"}
• Audio Spoof Confidence     : {audio_score * 100:.1f}% {"(SYNTHETIC VOICE CLONING DETECTED)" if audio_score > audio_thresh else "(Within Normal Parameters)"}
• Forensic Analyst Notes      : {sebi.get("reasoning", "Evidence points to non-compliant financial advisory distribution.")}

--------------------------------------------------------------------------------
3. APPLICABLE STATUTORY & REGULATORY FRAMEWORKS
--------------------------------------------------------------------------------
{chr(10).join(violations)}

--------------------------------------------------------------------------------
4. EXTRACTED FORENSIC EVIDENCE & VERBATIM TRANSCRIPT
--------------------------------------------------------------------------------
{evidence_text}

--------------------------------------------------------------------------------
5. RECOMMENDED REGULATORY ACTIONS (FOR SEBI ADJUDICATION)
--------------------------------------------------------------------------------
1. Issue directions under Section 11(1), 11(4) and 11B of the SEBI Act, 1992 restraining the respondent from securities market activities pending inquiry.
2. Direct impounding and disgorgement of illicit subscription revenues collected via private channels.
3. Coordinate with cyber crime cells / MeitY for domain takedowns under Section 69A of the IT Act.

================================================================================
Document generated by FinGuard Forensic Engine v4.0 (Local-First Architecture)
================================================================================
"""
    return complaint
